from sqlalchemy import Table, Column, Integer, Numeric, String, datetime, ForeignKey
from sqlalchemy.orm import DateTime
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, backref

Base = declarative_base()

class Vendor(Base):
    __tablename__ = 'vendor'

    Vendor_id = Column(Integer(), primary_key=True, autoincrement=True)
    Vendor_first_name = Column(String(50), nullable=False)
    Vendor_last_name = Column(String(50), nullable=False)
    Vendor_email = Column(String(100), nullable=False, unique=True)
    Vendor_phone = Column(String(20), nullable=False)
    Vendor_address = Column(String(100), nullable=False)
    Vendor_city = Column(String(50), nullable=False)
    Vendor_state = Column(String(2), nullable=False)
    Vendor_zip = Column(String(10), nullable=False)
    Vendor_country = Column(String(50), nullable=False)
    Vendor_notes = Column(String(200), nullable=True)
    Vendor_active = Column(Integer(), nullable=False, default=1)
    Vendor_created_at = Column(DateTime(), nullable=False, default=datetime.datetime.utcnow)
    Vendor_updated_at = Column(DateTime(), nullable=False, default=datetime.datetime.utcnow, onupdate=datetime.datetime)
    Vendor_deleted_at = Column(DateTime(), nullable=True)
    Vendor_deleted = Column(Integer(), nullable=False, default=0)
    Vendor_version = Column(Integer(), nullable=False, default=1)
    Vendor_created_by = Column(Integer(), nullable=False)
    Vendor_updated_by = Column(Integer(), nullable=False)
    Vendor_deleted_by = Column(Integer(), nullable=True)
    Vendor_vendor_type_id = Column(Integer(), ForeignKey('vendor_type.id'), nullable=False)
    Vendor_vendor_type = relationship("VendorType", backref="vendor")
    Vendor_vendor_status_id = Column(Integer(), ForeignKey('vendor_status.id'), nullable=False)
    Vendor_vendor_status = relationship("VendorStatus", backref="vendor")
    Vendor_vendor_category_id = Column(Integer(), ForeignKey('vendor_category.id'), nullable=False)
    Vendor_vendor_category = relationship("VendorCategory", backref="vendor")
    Vendor_vendor_subcategory_id = Column(Integer(), ForeignKey('vendor_subcategory.id'), nullable=False)
    Vendor_vendor_subcategory = relationship("VendorSubcategory", backref="vendor")
    Vendor_payment_term_id = Column(Integer(), ForeignKey('payment_term.id'), nullable=False)
    Vendor_payment_term = relationship("PaymentTerm", backref="vendor")
    Vendor_shipping_term_id = Column(Integer(), ForeignKey('shipping_term.id'), nullable=False)
    Vendor_shipping_term = relationship("ShippingTerm", backref="vendor")
    Vendor_tax_id = Column(Integer(), ForeignKey('tax.id'), nullable=False)
    Vendor_tax = relationship("Tax", backref="vendor")
    Vendor_currency_id = Column(Integer(), ForeignKey('currency.id'), nullable=False)
    Vendor_currency = relationship("Currency", backref="vendor")
    Vendor_language_id = Column(Integer(), ForeignKey('language.id'), nullable=False)
    Vendor_language = relationship("Language", backref="vendor")
    Vendor_time_zone_id = Column(Integer(), ForeignKey('time_zone.id'), nullable=False)
    Vendor_time_zone = relationship("TimeZone", backref="vendor")
    Vendor_vendor_group_id = Column(Integer(), ForeignKey('vendor_group.id'), nullable=False)
    Vendor_vendor_group = relationship("VendorGroup", backref="vendor")
    Vendor_vendor_contact_id = Column(Integer(), ForeignKey('vendor_contact.id'), nullable=False)
    Vendor_vendor_contact = relationship("VendorContact", backref="vendor")
    Vendor_vendor_address = relationship("VendorAddress", backref="vendor")
    Vendor_vendor_bank_id = Column(Integer(), ForeignKey('vendor_bank.id'), nullable=False)
    Vendor_vendor_bank = relationship("VendorBank", backref="vendor")
    Vendor_vendor_tax_id = Column(Integer(), ForeignKey('vendor_tax.id'), nullable=False)
    Vendor_vendor_tax = relationship("VendorTax", backref="vendor")
    Vendor_vendor_insurance_id = Column(Integer(), ForeignKey('vendor_insurance.id'), nullable=False)
    Vendor_vendor_insurance = relationship("VendorInsurance", backref="vendor")
    Vendor_vendor_license_id = Column(Integer(), ForeignKey('vendor_license.id'), nullable=False)
    Vendor_vendor_license = relationship("VendorLicense", backref="vendor")
    Vendor_vendor_certification_id = Column(Integer(), ForeignKey('vendor_certification.id'), nullable=False)
    Vendor_vendor_certification = relationship("VendorCertification", backref="vendor")
    Vendor_vendor_document_id = Column(Integer(), ForeignKey('vendor_document.id'), nullable=False)
    Vendor_vendor_document = relationship("VendorDocument", backref="vendor")
    Vendor_vendor_audit_id = Column(Integer(), ForeignKey('vendor_audit.id'), nullable=False)
    Vendor_vendor_audit = relationship("VendorAudit", backref="vendor")
    Vendor_vendor_rating_id = Column(Integer(), ForeignKey('vendor_rating.id'), nullable=False)
    Vendor_vendor_rating = relationship("VendorRating", backref="vendor")
    Vendor_vendor_review_id = Column(Integer(), ForeignKey('vendor_review.id'), nullable=False)
    Vendor_vendor_review = relationship("VendorReview", backref="vendor")
    Vendor_vendor_complaint_id = Column(Integer(), ForeignKey('vendor_complaint.id'), nullable=False)
    Vendor_vendor_complaint = relationship("VendorComplaint", backref="vendor")
    Vendor_vendor_feedback_id = Column(Integer(), ForeignKey('vendor_feedback.id'), nullable=False)
    Vendor_vendor_feedback = relationship("VendorFeedback", backref="vendor")
    Vendor_vendor_notification = relationship("VendorNotification", backref="vendor")
    Vendor_vendor_reminder_id = Column(Integer(), ForeignKey('vendor_reminder.id'), nullable=False)
    Vendor_vendor_reminder = relationship("VendorReminder", backref="vendor")
    Vendor_vendor_task_id = Column(Integer(), ForeignKey('vendor_task.id'), nullable=False)
    Vendor_vendor_task = relationship("VendorTask", backref="vendor")
    Vendor_vendor_project_id = Column(Integer(), ForeignKey('vendor_project.id'), nullable=False)
    Vendor_vendor_project = relationship("VendorProject", backref="vendor")
    Vendor_vendor_po_id = Column(Integer(), ForeignKey('vendor_po.id'), nullable=False)